### ISSUE TITLE
css 충돌로 인한 디자인 오류 

### ISSUE THREAD

**Issue by bm150** [jun9898/PlayData_Semi_Project#3]
### 세부내용 
작성된 Header.html 및 floating button에 사용되는 라이브러리가 및 css의 클래스 충돌로 인한 디자인 오류 발생.

#### 이슈항목
floating버튼 추가 : b69ad6e6a0e1cfa21067983271296cc27c69ade9
Header추가 : f07a7acdeb2fc81e180b454a457af70d673595f9

### 해결을 위한 고려사항
1. 프로젝트 진행간 적용할 프레임워크 및 라이브러리의 확정 또는 협의를 통한 적용

**Comment by jun9898** [comment]
앞으로 사용될 MDB 라이브러리에 대한 조원 모두의 숙지가 필요할 것 같습니다.

**Comment by bm150** [comment]
23.09.16 레이아웃 설정 작업간 MDB 라이브러리로 컨버팅 작업완료.
